dist: xenial
language: python
python: 3.5.2

before_install:
  - sudo apt-get install -y ruby ruby-dev rubygems build-essential libffi-dev devscripts
    libsystemd-dev
  - sudo gem install -n /usr/local/bin --no-ri --no-rdoc fpm

addons:
  apt:
    update: true

install:
  - pip install virtualenv sh plumbum

script:
  - sudo `which python3` package/make-deb.py

deploy:
  provider: bintray
  file: "./package/descriptor.json"
  user:
    secure: dgFRNX7PqhV3GI4fzgnBuxjd4TIwuJLMYLIrvkOVxxHgW67yvoSP2NLkGhYbNA5klLw6UR1vi9A3RwbLmfeAG3BlWMNY6qVMpxhVagwZaUmIC28LfFsxFrGzrAiOpc1OLDFT4iweS0+HglOvNCnFncpAbP3gvMCvdFd8AbS/y1lWe+vRXXY4JWnE7X8kMgn91RDX9gQ3+ycF8UEJ0DVLDObrhbT+2mNirb5ikCNReOeDYUbYpSsnNlJmR3G8bi/wuDWhV3b1g54jGp7z9Igw/WeAiONmSprXP44D/Gswh2kryALu4F5mbsd38gsoa0U5CPaHbjCMvQnLfORN853qElJ+RQb2T/err3UQTRYgGjE1qzs1A6SHuAZSg+Npy3C6aZ+N0CfaJW7R41MG1ycfRG5Xvo/8yq6//6YBTjsSChu15FsN+ADPEGXutzP2FNXm8Lm8QWmLd7BF1c/XY7m1Ey8fU3ThrYdNCH396Xs7yPdJ+956NZztlGsuO3NkOcWz+kQsJXYTMyTwnA0QMGddMvgdUQhzjJQyuc+okDq3BTg/h08M2khL0CafbaELUFH0Z0m+DVF9LOWMFcK5JeWrc7cWd2Do3p22yfTXcVVEWI6eHfDo3UDnFXwKgDLP2T2auFGARoz8wQy3IOO7913uAjsRjG4q8LsZ4DKxcg2qUe8=
  key:
    secure: vn6jmmO4Npb4TpdtyERrKAkHwTzktiHXI3xu70UPaL0yfBrvdhxOjxny4bYjDSqEVF70V2Dd5npSEO55n59fwOTd/IpA9XadPQWoZYDfwhKl8gA1Cmp7PSExvqpwXxCdIVgY3hD8oOW2OcXlBZO37APae/z/kWwYYTzPSlKbPT8Em3proE1EwvKVkki0TlDDEeui7U0YKYEb1mXx1PUajKhAUAOxRwgJS/N+2yzWVsQ/PzZT7KrBe0lNAKQI0Wxj7oTDn2FyViYgqOu1huXgyCRBRONncLbgA1Fj4VPg+8KPevVx2PEsetYdp76cGqMb+eYBDvu5o+gUfMRzN4vtwUe+heFB0roMgX4fcEcdiamys+AjExNtNNftCuV8H3oFsXJwlOEfctbZNrl2pC4c9qZPN23SPXoXo58XVIqoL4eG80QeaesQWBnZOCGjS6piBX5wM9B+O3CKGlx+TIUgEBITcxu1tod9V9p+wnpYKX41qQxtYSwYKSQuwneRvRV+gLbnEZ7QTj4vX8GFEyX1oigZOud7BOJi+4tE7+ovpK9ZIoM9FT2p9s2rAK/fExyQVC8Xhtt+N5OxTeTsTbn7RihV57JWT7n0U0a9gLoOYW0UVRP/Ur84L5DMAZah7C8OOqNpbhre8QdQMgcHCvVZHojNg/CrZ6bxWOCG4nzVOlw=
  skip_cleanup: true
