dist: bionic
language: python
python: 3.6

before_install:
  - sudo apt-get install -y ruby ruby-dev rubygems build-essential libffi-dev devscripts
    libsystemd-dev
  - sudo gem install -n /usr/local/bin --no-ri --no-rdoc fpm

addons:
  apt:
    update: true

install:
  - pip install virtualenv sh plumbum

script:
  - sudo `which python3` package/make-deb.py

deploy:
  provider: bintray
  file: "./package/descriptor.json"
  user:
    secure: RKS8fcnOyaxtB2g1BVaaRLtdwJTZJiriQ1SQ3VB3/aQGfV689rOuWRBf2EIdf1jrX3NTHB8H6VLbjZ+fWD3TSBZOgvXm6Vkiax2/vZi73LXlKdvz63HS4QWRYo2fAUozJNZwpxzhsitvXooBqhaCUgdymo632m4ofH4NC9cN5cXyulB8JHMszjZdl8jjgO5S8zED/5V8XzssDYzUe3/DETvEgQ9Ztw+zFb39hVCi6aAoQnT+qLWS9rdholwSuaLFKOT+kb3nOUA04Jvi9SzkhfCVdziF2wVCwzrLx/Ytj6p4nRLf14HBwwDUAcOEc9OnpDT/mpSawwflWA3ThZG/0r7QF0CYkfO2mOtHj0Hfds9A5XTYue2pSQovyFVvjehuVObL9ZkYKzRcgv9BqAlAXnxHqn0G4Wy537392UDaTIE/NJV24uT+b7wPLKb6AMUbn93KxWt3Lp5WJYjnN839iKzNXLa6pL1VGUbYyEpyjCbNlErIVJHdVDdiMIBVW1UcTiqKFozLM19ZdGyh22+mZ2rQzVntzBZCI8r8vgS79H5wTylbPjp+ceV9XhRXm1HZoh560pTvqygk7Z0BK2sBS1u6Of2b8ko09/l5eUcMoE0zcjGcFcoQ9XcS5YtcmDRUaYS6pY9LbbM5KQs4vj/Qdn1xQlX2FEwCBO2TnAD/Nt4=
  key:
    secure: OW7zHKvtG2Vf0Sah+ObH7U5/RHJypDXkqlLylhtgYTFU1VXQZnnurHm6dgMvWOfxiLV7Jbao7/tnoINNLz07LMw4mxpc4IPuKjn9Bj5dcQMt+U83Rk3eE4dxbk2j2RTWzxgWWxEFd/OfNgqZNOk7P9xy8dI2ypfnvrBg3x0JjVYVTU4UWUgIKcAU/5obsfj1dpZd/7dKF9acV51PvQHE8dtPzInqMvMjzjKGzzFqMu02v/pQAgtHCnS2JcADQo+UJon3MxPVqLQecszTUZOu15ir5C44Vaauyc+cJ2+XfuyrgofriPNwqy/3aSzvA8WpWmTdla+qreMaC4Pu7gVacYREa3iRZjm6+hFRxSNFgN+7ZW2PtrwWjyu3FSjq+JaDFkfpWP2nEUlEnNLCmLQzkjYh6/mMNqsL0b4w1uIIC4NHuVPPiMrjt2tXnWrgjuocA477qYv20sxFqBn53l8JzBwSj1u+zRiye+1tRpsWSUkz1sgl3OAbC0g3vaiSadAdxXL6h++3f4USDgpQdY64mdRJRuFN5ZxQGopEQCcXVDztTDv0pYLBm3QI3gBug0C0pcBkl5jryb3/SJ6LG3RTgVn6e+3t7BMLfzeirPR74hKVgh1xL7mjVk9fBusL5Td5qrarFOJHeWNqL9t8E16GMSj/fgNbyxSNHTx5bCeF52o=
  skip_cleanup: true
