on:
  push:
    branches:
      - master

name: Build deb package

env:
    PACKAGE_VERSION: "0.9.2"

jobs:
  xenial:
    name: Build xenial
    runs-on: ubuntu-16.04
    container:
      image: asteny/fpm-python-docker:xenial-3.7
    steps:
    - uses: actions/checkout@v2
    - name: build deb package
      run: /home/env/bin/python3 package/make-deb.py
    - name: ls & rename
      run: |
          ls -la package/
          mv package/nginx2es_${{ env.PACKAGE_VERSION }}-0_amd64.deb package/nginx2es_${{ env.PACKAGE_VERSION }}-0-xenial_amd64.deb
    - name: Upload deb package to Bintray
      uses: bpicode/github-action-upload-bintray@master
      with:
        file: package/nginx2es_${{ env.PACKAGE_VERSION }}-0-xenial_amd64.deb
        api_user: asten
        api_key: ${{ secrets.BINTRAY_API_KEY }}
        repository_user: asten
        repository: nginx2es
        package: nginx2es
        version: ${{ env.PACKAGE_VERSION }}
        upload_path: pool/main/n/nginx2es
        publish: 1
        calculate_metadata: true
        deb_distribution: xenial
        deb_component: main
        deb_architecture: amd64
  bionic:
    name: Build bionic
    runs-on: ubuntu-18.04
    container:
      image: asteny/fpm-python-docker:bionic-3.7
    steps:
    - uses: actions/checkout@v2
    - name: build deb package
      run: /home/env/bin/python3 package/make-deb.py
    - name: ls & rename
      run: |
          ls -la package/
          mv package/nginx2es_${{ env.PACKAGE_VERSION }}-0_amd64.deb package/nginx2es_${{ env.PACKAGE_VERSION }}-0-bionic_amd64.deb
    - name: Upload deb package to Bintray
      uses: bpicode/github-action-upload-bintray@master
      with:
        file: package/nginx2es_${{ env.PACKAGE_VERSION }}-0-bionic_amd64.deb
        api_user: asten
        api_key: ${{ secrets.BINTRAY_API_KEY }}
        repository_user: asten
        repository: nginx2es
        package: nginx2es
        version: ${{ env.PACKAGE_VERSION }}
        upload_path: pool/main/n/nginx2es
        publish: 1
        calculate_metadata: true
        deb_distribution: bionic
        deb_component: main
        deb_architecture: amd64
