DEFAULT_TEMPLATE = {
   "index_patterns":[
      "nginx-*"
   ],
   "template":{
      "settings":{
         "index":{
            "refresh_interval":"10s",
            "mapping":{
               "total_fields":{
                  "limit":"5000"
               }
            },
            "merge":{
               "policy":{
                  "max_merged_segment":"5g"
               }
            },
            "unassigned":{
               "node_left":{
                  "delayed_timeout":"5m"
               }
            },
            "codec":"best_compression"
         }
      },
      "mappings":{
         "date_detection": False,
         "properties":{
            "@timestamp":{
               "format":"date_optional_time",
               "type":"date"
            },
            "remote_addr":{
               "type":"ip"
            },
            "geoip":{
               "type":"geo_point"
            },
            "query_geo":{
               "type":"geo_point"
            },
            "status":{
               "type":"long"
            },
            "request":{
               "type":"text",
               "fields":{
                  "raw":{
                     "type":"keyword",
                     "norms": False
                  }
               }
            },
            "request_path":{
               "type":"text",
               "fields":{
                  "raw":{
                     "type":"keyword",
                     "norms": False
                  }
               }
            },
            "request_qs":{
               "type":"text",
               "fields":{
                  "raw":{
                     "type":"keyword",
                     "norms": False
                  }
               }
            }
         },
         "dynamic": True,
         "dynamic_templates":[
            {
               "long_fields":{
                  "match":"*",
                  "match_mapping_type":"long",
                  "mapping":{
                     "type":"long"
                  }
               }
            },
            {
               "string_fields":{
                  "mapping":{
                     "type":"keyword",
                     "norms": False
                  },
                  "match_mapping_type":"string",
                  "match":"*"
               }
            }
         ]
      },
      "aliases":{

      }
   },
   "version":4
}
